### ISSUE TITLE
Invisible output

### ISSUE THREAD

**Issue by GiusTex** [marella/chatdocs#19]
I asked two things in italian, the first time it worked, the second I got this (no error log):
Input: `Nella fase di stima del valore di mercato, l'income approach impiega due calcoli differenti, quali, puoi descriverli?`
Output:
```




























helpful il mettere e una o Comment on micro-
```
(blank lines, then at the end an incoherent partial sentence, and then the sources). It's like if the output is in the lines there, but invisible, not printed.

Console: `[2023-06-16 15:14:19 +0200] [66608] [INFO] 127.0.0.1:53010 GET /favicon.ico 1.1 404 207 997`
I'm using the gpu (rtx 3060) on windows 11:
```
ctransformers:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-GGML
  model_file: Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin
  model_type: llama
  config:
    context_length: 1024
    gpu_layers: 50

huggingface:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-HF
  pipeline_kwargs:
    max_new_tokens: 256
  device: 0

gptq:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-GPTQ
  model_file: Wizard-Vicuna-7B-Uncensored-GPTQ-4bit-128g.no-act-order.safetensors
  pipeline_kwargs:
    max_new_tokens: 256
  device: 0
```
