### ISSUE TITLE
won't use gpu

### ISSUE THREAD

**Issue by TheFinality** [marella/chatdocs#21]
im trying to have ctransformers use gpu but it won't work.

my chatdocs.yml: 

```yml
ctransformers:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-GGML
  model_file: Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin
  model_type: llama
  config:
    gpu_layers: 50


llm: ctransformers
```

**Comment by marella** [comment]
Can you please try reinstalling `ctransformers` with CUDA enabled:

```sh
pip uninstall ctransformers --yes
CT_CUBLAS=1 pip install ctransformers --no-binary ctransformers
```

**Comment by TheFinality** [comment]
now i think it only uses it for a few seconds, then stops using the gpu. why is that? after this it just hovers around 1-2% usage.
![image](https://github.com/marella/chatdocs/assets/67923032/6132219e-28b7-4785-903e-a4fb3c756e5f)

**Comment by LazyCat420** [comment]
running into the same problem as well I followed the instructions above and got it to run but it uses the gpu for only a second then the CPU starts to go up to 40%. 

Tried setting CT_CUBLAS=1 but still didn't seem to work. 

Here is the yml 

ctransformers:
  model: F:/AI_Scripts/chatdocs/model/wizard-mega-13B.ggmlv3.q8_0.bin
  model_file: wizard-mega-13B.ggmlv3.q8_0.bin
  model_type: llama
  config:
    gpu_layers: 50

llm: ctransformers

**Comment by marella** [comment]
Did you notice any performance drop if you don't set `gpu_layers`?

Recently llama.cpp added full GPU acceleration (https://github.com/ggerganov/llama.cpp/pull/1827) which is added to `ctransformers` in `0.2.9` today. Can you please try updating `ctransformers` to `0.2.9` and see if there is any improvement in speed:

```sh
CT_CUBLAS=1 pip install 'ctransformers>=0.2.9' --no-binary ctransformers
```

Also try setting `threads: 1` in your config:

```yml
ctransformers:
  config:
    threads: 1
```

**Comment by LazyCat420** [comment]
I reinstalled ctransformers 0.2.9 but it only worked when I removed the quotes. I tried fixing it in conda and venv and ran into the same issues. I'm running cuda 11.8 with CUDA version 12.2 . I set threads to 1 and removed gpu_layers and now its basically doing nothing cpu is set to 3% and gpu is at 1%. 


Here is how i installed it on venv and conda 

set CT_CUBLAS=1
pip install ctransformers>=0.2.9 --no-binary ctransformers

when i check pip list its there under ctransformers 0.2.9

this is the yml

ctransformers:
  model: F:\AI_Scripts\chatdocs\model\wizard-mega-13B.ggmlv3.q8_0.bin
  model_file: wizard-mega-13B.ggmlv3.q8_0.bin
  model_type: llama
  config:
    context_length: 1024
    threads: 1

**Comment by marella** [comment]
You should set `gpu_layers` also. I just wanted to see if there is any performance difference when you don't set `gpu_layers`. So you can add it back.

```yml
ctransformers:
  config:
    gpu_layers: 100
    threads: 1
```

By setting both `gpu_layers` and `threads: 1`, it should utilize GPU more.

**Comment by TheFinality** [comment]
did this, and same as @LazyCat420 it barely uses cpu now, and it doesn't use gpu either.

**Comment by nilvaes** [comment]
> now i think it only uses it for a few seconds, then stops using the gpu. why is that? after this it just hovers around 1-2% usage. ![image](https://user-images.githubusercontent.com/67923032/246636496-6132219e-28b7-4785-903e-a4fb3c756e5f.png)

here in gpu tab you can see that its using your gpu vram (dedicated gpu memory usage). I think its the important part. If you use only cpu, you will see that gpu vram tab will stay same, but if you use gpu that line will go higher as in the screenshot.

In short, its working, if its whats expected.
When i used only my cpu i got answers in 70 secs. but after gpu i got answers in 35 or 37 secs. (It might be still slow i have low specs)

**Comment by TheFinality** [comment]
but shouldnt the utilization also go up? in that picture it is still at 1%.

**Comment by LazyCat420** [comment]
I got gpu to work on GPTQ I would suggest trying that if you haven't yet. It was using 12GB of vram and 95% of the card the whole time. I just followed the instructions to install chatdocs with GPTQ and it worked. Only issue I ran into was I had to reinstall protobuf 3.2 in order to download the model. 

This was the yml 

gptq:
  model: TheBloke/Nous-Hermes-13B-GPTQ
  model_file: nous-hermes-13b-GPTQ-4bit-128g.no-act.order.safetensors
  device: 0
    
llm: gptq

**Comment by marella** [comment]
Thanks @nilvaes for the explanation.

I suggest simply looking at the response generation speed instead of the GPU usage numbers.

Try out both the CPU and GPU configs and see which gives better performance for your system.

CPU config:

```yml
ctransformers:
  config:
    gpu_layers: 0
    threads: 4 # set it to the number of physical cores your CPU has
```

GPU config:

```yml
ctransformers:
  config:
    gpu_layers: 100
    threads: 1
```

You can also try other models like GPTQ as LazyCat420 mentioned and pick the one that works best for your system.
