### ISSUE TITLE
The answers get cut off in the middle when it gives longer answers

### ISSUE THREAD

**Issue by Ananderz** [marella/chatdocs#28]
Hi, is there any way to increase the lenght of the responses, the answers just cut off in the middle and there is no way to continue the prompt

**Comment by marella** [comment]
Hi, you can increase `max_new_tokens` (default is `256`):

```yml
ctransformers:
  config:
    max_new_tokens: 500 # increase this value
```
