### ISSUE TITLE
Any way to set temperature in the yaml file?

### ISSUE THREAD

**Issue by Ananderz** [marella/chatdocs#40]
Hi,

I have seen quite a bit of hallucinations with the model. I am trying to find a way to set temperature. Is there something I can do in the yml file?

**Comment by marella** [comment]
Hi, you can set temperature for ctransformers/hf/gptq models using:

```yml
ctransformers:
  config:
    temperature: 0.8

huggingface:
  pipeline_kwargs:
    temperature: 0.8

gptq:
  pipeline_kwargs:
    temperature: 0.8
```
