### ISSUE TITLE
French language support

### ISSUE THREAD

**Issue by yann83** [marella/chatdocs#98]
Hello 
I'd trie many things but I'm unable to run your program in french. Someone can help me ?

```
embeddings:
  model: dangvantuan/sentence-camembert-large

llm: huggingface

huggingface:
 model: intfloat/multilingual-e5-large
```
